### ISSUE TITLE
Multi-use footprint

### ISSUE THREAD

**Issue by gcormier** [sirhcel/dl3000-adapters#1]
I am designing a variant which can use a more-common footprint in North America. Both Harwin ( https://www.digikey.ca/en/products/detail/harwin-inc/M3498-99/4953082 ) and Cinch Connectivity (https://www.digikey.ca/en/products/detail/cinch-connectivity-solutions-johnson/105-0752-001/5887 ) have similar jacks that use the same footprint.

I could do a separate footprint altogether, or, add a 3rd hole to your existing design (removing your center pin, unsure on the point of that?) so it could accommodate all of these in 1 board. Any thoughts?

![image](https://user-images.githubusercontent.com/8388983/101521697-2d997580-3954-11eb-95f6-3cd0eb1ee207.png)

We would need to remove the circle pad pointed to.

**Comment by sirhcel** [comment]
Thanks for your feedback!

> I could do a separate footprint altogether, or, add a 3rd hole to your existing design (removing your center pin, unsure on the point of that?) so it could accommodate all of these in 1 board. Any thoughts?

Having the option to fit either connector would make the board more versatile. So I would opt for the 3rd hole.

The Hirschmann connector offers a hole for additionally screwing it to the board. Looking at your image and a board on my desk, it looks like I have messed up the drill diameter. The one in the board is actually way to small. So please go ahead and remove the hole. I've used the connectors on several test jigs and never felt like a screw was needed.

**Comment by gcormier** [comment]
Okay I submitted a PR. I've also ordered some PCB's so I can take a picture of them over Christmas once they arrive!

**Comment by sirhcel** [comment]
Awesome! Thank you very much! Let's have the conversation continued at #2.

**Comment by gcormier** [comment]
![image](https://user-images.githubusercontent.com/8388983/103094449-865f4400-45cb-11eb-992f-21ae2dc885b9.png)

So I've found a CalTest version that is quite big. It would mean increasing the PCB size.

What are your thoughts?

**Comment by sirhcel** [comment]
The connector from CalTest is indeed a bit clunky. And I'm a bit afraid of the big lever it introduces.

DigiKey does not seem to have a big selection of PCB-mount banana plug sockets. What about another distributor?
* Newark seems to have the [Hirschmann 973582100 in stock](https://www.newark.com/hirschmann-testmeasurement/973582100/test-socket-pcb-4mm-black/dp/06WX5874) in the US and Canada. Though they are sold only in packs of five. I see that this might not be convenient for building up just a single adapter.
* Newark also offers the [DELTRON 571-0100-01](https://www.newark.com/deltron-components/571-0100-01/test-point-socket-pcb-4mm-10a/dp/93K4533) which is sold individually. And it looks that we could use a multi-part footprint at a first glance.

I also searched searched through DigiKeys selection and apart of the CalTest connector I only found two connectors from Pomona which are quite pricy:
* The [73099](https://www.digikey.ca/en/products/detail/pomona-electronics/73099-2/10483465) as an angled variant which likelky requires increasing the PCB.
* The [73096](https://www.digikey.ca/en/products/detail/pomona-electronics/73096-2/10483466) as a vertical variant. This is an interesting alternative to me in case you have sitting another instrument right next to your DL3000 and a plug in the angled connector forms quite a big "cantilever".

So what about working aout a joint-footprint for the original Hirschmann and the DELTRON connector? I will give the vertical connector from Pomona some thoughts, may be it still fits on the same PCB as well.

**Comment by gcormier** [comment]
I think the 73099 from Pomona would be the preferred option for North America. It is stocked by both Digikey and Mouser which are probably the most popular distributors here.

**Comment by sirhcel** [comment]
Alright. Then we should be able to make another multi footprint board for the Pomona 73099. It looks like we have to slightliy increase the board vertically "downwards" to keep the clearance to the DL3000 binding posts. When placing the Pomona jacks almost back-to-back in the middle of the board, we should have no need to extend the board horizontally as well.

Could you add this footprint to the banana jack board? I will do the housekeeping and update the manufacturing data and the project as OSH Park.

**Comment by gcormier** [comment]
Sure I will design the footprint and add it.

**Comment by gcormier** [comment]
![image](https://user-images.githubusercontent.com/8388983/103792407-9afefb80-5011-11eb-864f-d1073da7ddf6.png)


So, the height will definitely need to increase slightly.

I've put each in a different position to get your opinion. Either of these, the connector is hanging off the side of the board. The left position keeps the width of the board the same. The right position would require us to increase the width of the PCB. 

I'll send a PR so you can get the files and play around with the position.

**Comment by sirhcel** [comment]
Thanks for the PR! I would place the Pomona jacks back to back and - after playing around with them - on a separate board. In this position their solder joints should also not interfere with the rubber feet of the DL3000 case.

I noticed that the lower left mounting PTH (on J5 in https://github.com/sirhcel/dl3000-adapters/issues/1#issuecomment-755452604) is slightly offset. Once I started looking at the datasheet in detail, I would go for rectangular/oval PTHs. This would allow to insert the mounting pins completely and place the plastic housing of this jack flat onto the PCB.

<img width="581" alt="pomona-jacks-back-to-back" src="https://user-images.githubusercontent.com/8770800/104102855-4a9ccd80-529f-11eb-9f26-6dd766041c4a.png">

You could look at the updated footprint and new board [here](https://github.com/sirhcel/dl3000-adapters/blob/d006e15b4c36e5e3f11c739fdd69e3a85d045e80/dl3000-adapters.kicad_pcb). Could you please cross-check footprint and placement?

**Comment by sirhcel** [comment]
After fixing my remote for your PR, I added my update to #3 as well.

**Comment by sirhcel** [comment]
I ordered some boards as of https://github.com/sirhcel/dl3000-adapters/issues/1#issuecomment-757332319 and the new footprint works out. Let's go with individual boards for the different footprints then.
